name: kisgeri24
description: Kisgeri24 Climbing Competition Application
version: 1.0.0+1
publish_to: "none"
environment:
  sdk: "3.2.4"

dependencies:
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  email_validator: ^2.1.16

  logger: ^2.0.1

  shared_preferences: ^2.0.15
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  flutter_facebook_auth: ^6.0.0
  http: ^1.1.0
  image_picker: ^1.0.1
  cached_network_image: ^3.2.2
  smooth_page_indicator: ^1.0.0+2
  the_apple_sign_in: ^1.1.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  url_launcher: ^6.1.6
  file_picker: ^5.2.2

  flutter:
    sdk: flutter
  background_fetch: ^1.2.0
  equatable: ^2.0.3

  cupertino_icons: ^1.0.5
  firebase_database: ^10.4.0

  flutter_cupertino_datetime_picker: ^3.0.0
  intl: ^0.18.1
  numberpicker: ^2.1.2
  date_time_picker_widget: ^2.0.0
  expandable_menu: ^0.0.5
  popup_menu: ^2.0.0
  pie_menu: ^1.3.0
  star_menu: ^3.1.4
  flutter_local_notifications: ^15.1.0+1
  flutter_feather_icons: ^2.0.0+1
  responsive_sizer: ^3.3.0


dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  lint: ^2.0.0
  mockito: ^5.4.2
  test: ^1.24.1

flutter_launcher_icons:
  android: "ic_launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher_round"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/ic_launcher_round"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/ic_launcher_round"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/ic_launcher_round"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_launcher_round.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
